// Platform-specific keywords for SEO optimization
export const PLATFORM_KEYWORDS = {
  // Core keywords from user request
  core: [
    'cover',
    'cover image',
    'cover maker',
    'cover image generator',
    'thumbnail',
    'thumbnail maker',
    'thumbnail maker',
    'youtube thumbnail maker',
    'youtube thumbnail maker',
    'youtube cover maker',
    'poster',
    'poster maker',
    'poster image maker',
    'poster image generator',
    'tiktok thumbnail maker',
    // Sora 2 keywords
    'sora 2',
    'sora2',
    'openai sora 2',
    'sora 2 ai',
    'sora 2 video generator',
    'sora 2 video ai',
    'sora 2 model',
    'ai video generator',
    'text to video ai',
    'ai video creation',
    'ai video maker',
    'video generation ai',
    'ai video cover',
    'ai video thumbnail',
    'sora 2 thumbnail generator',
    'sora 2 cover maker',
    'sora 2 video covers',
    'sora 2 youtube thumbnails',
    'sora 2 content creation',
    'sora 2 api',
    'sora 2 integration',
    'sora 2 workflow',
    'sora 2 templates',
    'sora 2 effects',
    'sora 2 vs midjourney',
    'sora 2 vs stable diffusion',
    'sora 2 alternative',
    'best sora 2 covers',
    'sora 2 for youtube',
    'sora 2 for tiktok',
    'sora 2 for content creators',
    'sora 2 video editing',
    'sora 2 motion graphics',
  ],

  // YouTube platform keywords
  youtube: [
    'YouTube thumbnail maker',
    'YouTube thumbnail generator',
    'YouTube cover maker',
    'YouTube cover creator',
    'YouTube poster maker',
    'YouTube thumbnail designer',
    'YouTube cover image generator',
    'YouTube poster image maker',
    'youtube thumbnail maker',
    'youtube cover maker',
    'YouTube thumbnail size',
    'clickbait thumbnail generator',
    'YouTube thumbnail templates',
    'free thumbnail maker',
    'YouTube cover design',
    'YouTube banner maker',
    'YouTube channel cover',
    'YouTube video thumbnail',
    'YouTube gaming thumbnail',
    'YouTube tutorial thumbnail',
    'YouTube review thumbnail',
    'YouTube vlog thumbnail',
    'YouTube music thumbnail',
    'YouTube comedy thumbnail',
    'YouTube educational thumbnail',
    'YouTube thumbnail background',
    'YouTube thumbnail text',
    'YouTube thumbnail overlay',
    'YouTube thumbnail effects',
    'YouTube thumbnail fonts',
    // Sora 2 YouTube integration
    'sora 2 youtube thumbnails',
    'sora 2 youtube covers',
    'youtube sora 2 integration',
    'sora 2 youtube video maker',
    'sora 2 youtube content',
  ],

  // TikTok platform keywords
  tiktok: [
    'TikTok cover maker',
    'TikTok thumbnail maker',
    'TikTok thumbnail generator',
    'TikTok cover creator',
    'TikTok poster maker',
    'TikTok cover image generator',
    'TikTok thumbnail designer',
    'TikTok poster image maker',
    'tiktok thumbnail maker',
    'TikTok video cover',
    'vertical video thumbnail',
    'TikTok cover design',
    'TikTok thumbnail size',
    'viral TikTok covers',
    'TikTok cover templates',
    'mobile video covers',
    'TikTok content creator tools',
    'TikTok story cover maker',
    'TikTok banner maker',
    'TikTok profile cover',
    'TikTok dance cover',
    'TikTok comedy cover',
    'TikTok lip sync cover',
    'TikTok tutorial cover',
    'TikTok beauty cover',
    'TikTok fashion cover',
    'TikTok food cover',
    'TikTok travel cover',
    'TikTok fitness cover',
    'TikTok gaming cover',
    'TikTok music cover',
    'TikTok duet cover',
    'TikTok transition cover',
    'TikTok challenge cover',
    'TikTok trend cover',
    // Sora 2 TikTok integration
    'sora 2 tiktok covers',
    'sora 2 tiktok thumbnails',
    'tiktok sora 2 integration',
    'sora 2 tiktok video maker',
    'sora 2 tiktok content',
  ],

  // Spotify platform keywords
  spotify: [
    'Spotify cover art',
    'Spotify cover maker',
    'Spotify thumbnail maker',
    'Spotify poster maker',
    'Spotify cover image generator',
    'Spotify album cover maker',
    'Spotify playlist cover maker',
    'Spotify poster image generator',
    'album cover maker',
    'music cover generator',
    'album art creator',
    'Spotify cover design',
    'music cover design',
    'album artwork creator',
    'Spotify playlist cover',
    'Spotify artist cover',
    'Spotify podcast cover',
    'Spotify single cover',
    'Spotify EP cover',
    'Spotify compilation cover',
    'Spotify remix cover',
    'Spotify live cover',
    'Spotify acoustic cover',
    'Spotify instrumental cover',
    'Spotify electronic cover',
    'Spotify rock cover',
    'Spotify pop cover',
    'Spotify hip hop cover',
    'Spotify jazz cover',
    'Spotify classical cover',
    'Spotify country cover',
    'Spotify indie cover',
    'Spotify alternative cover',
    'Spotify metal cover',
    'Spotify punk cover',
  ],

  // Instagram platform keywords
  instagram: [
    'Instagram post maker',
    'Instagram cover maker',
    'Instagram thumbnail maker',
    'Instagram poster maker',
    'Instagram story cover maker',
    'Instagram post image generator',
    'Instagram cover image maker',
    'Instagram poster image generator',
    'Instagram post designer',
    'Instagram story designer',
    'Instagram thumbnail generator',
    'square post design',
    'Instagram story cover',
    'Instagram post templates',
    'Instagram cover design',
    'Instagram feed cover',
    'Instagram highlight cover',
    'Instagram reel cover',
    'Instagram IGTV cover',
    'Instagram carousel cover',
    'Instagram grid cover',
    'Instagram aesthetic cover',
    'Instagram fashion cover',
    'Instagram beauty cover',
    'Instagram food cover',
    'Instagram travel cover',
    'Instagram fitness cover',
    'Instagram lifestyle cover',
    'Instagram business cover',
    'Instagram influencer cover',
    'Instagram brand cover',
    'Instagram product cover',
    'Instagram event cover',
    'Instagram wedding cover',
    'Instagram birthday cover',
  ],

  // Twitch platform keywords
  twitch: [
    'Twitch thumbnail maker',
    'Twitch cover maker',
    'Twitch thumbnail generator',
    'Twitch poster maker',
    'Twitch stream cover maker',
    'Twitch thumbnail designer',
    'Twitch cover image generator',
    'Twitch poster image generator',
    'stream thumbnail generator',
    'gaming thumbnail maker',
    'Twitch overlay creator',
    'gaming cover maker',
    'stream cover design',
    'Twitch thumbnail size',
    'gaming thumbnail templates',
    'Twitch channel cover',
    'Twitch stream overlay',
    'Twitch panel cover',
    'Twitch offline cover',
    'Twitch schedule cover',
    'Twitch about cover',
    'Twitch rules cover',
    'Twitch donation cover',
    'Twitch subscriber cover',
    'Twitch follower cover',
    'Twitch moderator cover',
    'Twitch VIP cover',
    'Twitch emotes cover',
    'Twitch badges cover',
    'Twitch alerts cover',
    'Twitch scenes cover',
    'Twitch transitions cover',
    'Twitch intermission cover',
    'Twitch starting soon cover',
    'Twitch be right back cover',
  ],

  // LinkedIn platform keywords
  linkedin: [
    'LinkedIn cover maker',
    'LinkedIn thumbnail maker',
    'LinkedIn poster maker',
    'LinkedIn cover image generator',
    'LinkedIn banner maker',
    'LinkedIn header maker',
    'LinkedIn poster image generator',
    'LinkedIn cover creator',
    'professional cover generator',
    'LinkedIn header designer',
    'LinkedIn banner creator',
    'professional cover design',
    'LinkedIn cover size',
    'LinkedIn profile cover',
    'business cover maker',
    'LinkedIn company cover',
    'LinkedIn personal cover',
    'LinkedIn career cover',
    'LinkedIn networking cover',
    'LinkedIn industry cover',
    'LinkedIn professional cover',
    'LinkedIn business cover',
    'LinkedIn marketing cover',
    'LinkedIn sales cover',
    'LinkedIn consulting cover',
    'LinkedIn coaching cover',
    'LinkedIn speaking cover',
    'LinkedIn author cover',
    'LinkedIn thought leader cover',
    'LinkedIn expert cover',
    'LinkedIn consultant cover',
    'LinkedIn freelancer cover',
    'LinkedIn entrepreneur cover',
    'LinkedIn executive cover',
    'LinkedIn manager cover',
  ],

  // Twitter/X platform keywords
  twitter: [
    'Twitter cover maker',
    'Twitter thumbnail maker',
    'Twitter poster maker',
    'Twitter cover image generator',
    'Twitter header maker',
    'Twitter banner maker',
    'Twitter poster image generator',
    'X cover maker',
    'X thumbnail maker',
    'X poster maker',
    'Twitter profile cover',
    'Twitter header design',
    'Twitter banner design',
    'Twitter cover size',
    'Twitter header size',
    'Twitter profile header',
    'Twitter business cover',
    'Twitter personal cover',
    'Twitter brand cover',
    'Twitter influencer cover',
    'Twitter content creator cover',
    'Twitter journalist cover',
    'Twitter analyst cover',
    'Twitter consultant cover',
    'Twitter speaker cover',
    'Twitter author cover',
    'Twitter expert cover',
    'Twitter thought leader cover',
    'Twitter professional cover',
    'Twitter career cover',
    'Twitter networking cover',
    'Twitter industry cover',
    'Twitter marketing cover',
    'Twitter sales cover',
    'Twitter business cover',
  ],

  // Facebook platform keywords
  facebook: [
    'Facebook cover maker',
    'Facebook thumbnail maker',
    'Facebook poster maker',
    'Facebook cover image generator',
    'Facebook page cover maker',
    'Facebook group cover maker',
    'Facebook poster image generator',
    'Facebook cover creator',
    'Facebook profile cover',
    'Facebook page cover',
    'Facebook group cover',
    'Facebook event cover',
    'Facebook business cover',
    'Facebook personal cover',
    'Facebook brand cover',
    'Facebook marketing cover',
    'Facebook advertising cover',
    'Facebook business page cover',
    'Facebook fan page cover',
    'Facebook community cover',
    'Facebook group admin cover',
    'Facebook moderator cover',
    'Facebook event organizer cover',
    'Facebook business owner cover',
    'Facebook entrepreneur cover',
    'Facebook consultant cover',
    'Facebook coach cover',
    'Facebook speaker cover',
    'Facebook author cover',
    'Facebook expert cover',
    'Facebook influencer cover',
    'Facebook content creator cover',
    'Facebook marketer cover',
    'Facebook sales cover',
    'Facebook networking cover',
  ],

  // Pinterest platform keywords
  pinterest: [
    'Pinterest cover maker',
    'Pinterest thumbnail maker',
    'Pinterest poster maker',
    'Pinterest pin cover maker',
    'Pinterest cover image generator',
    'Pinterest board cover maker',
    'Pinterest poster image generator',
    'Pinterest cover creator',
    'Pinterest board cover',
    'Pinterest pin cover',
    'Pinterest profile cover',
    'Pinterest business cover',
    'Pinterest brand cover',
    'Pinterest marketing cover',
    'Pinterest advertising cover',
    'Pinterest influencer cover',
    'Pinterest content creator cover',
    'Pinterest blogger cover',
    'Pinterest designer cover',
    'Pinterest artist cover',
    'Pinterest photographer cover',
    'Pinterest chef cover',
    'Pinterest fashion cover',
    'Pinterest beauty cover',
    'Pinterest home decor cover',
    'Pinterest DIY cover',
    'Pinterest crafts cover',
    'Pinterest travel cover',
    'Pinterest fitness cover',
    'Pinterest health cover',
    'Pinterest parenting cover',
    'Pinterest education cover',
    'Pinterest business cover',
    'Pinterest entrepreneurship cover',
    'Pinterest lifestyle cover',
  ],

  // Chinese platforms
  chinese: {
    xiaohongshu: [
      'Xiaohongshu cover maker',
      'Xiaohongshu thumbnail maker',
      'Xiaohongshu poster maker',
      'RED note cover maker',
      'Little Red Book cover maker',
      '小红书封面制作器',
      '小红书缩略图制作器',
      '小红书海报制作器',
      'Xiaohongshu cover',
      'RED note cover',
      'Little Red Book cover',
      'Chinese social media cover',
      '小红书封面设计',
      '小红书笔记封面',
      '小红书封面模板',
      '小红书美妆封面',
      '小红书穿搭封面',
      '小红书美食封面',
      '小红书旅行封面',
      '小红书护肤封面',
      '小红书健身封面',
      '小红书家居封面',
      '小红书母婴封面',
      '小红书教育封面',
      '小红书职场封面',
      '小红书情感封面',
      '小红书生活封面',
      '小红书种草封面',
      '小红书测评封面',
      '小红书分享封面',
      '小红书推荐封面',
      '小红书热门封面',
      '小红书爆款封面',
      '小红书网红封面',
      '小红书达人封面',
    ],

    wechat: [
      'WeChat cover maker',
      'WeChat thumbnail maker',
      'WeChat poster maker',
      'WeChat moments cover maker',
      'WeChat article cover maker',
      '微信封面制作器',
      '微信缩略图制作器',
      '微信海报制作器',
      'WeChat cover',
      'WeChat moments cover',
      'WeChat article cover',
      'Chinese social media design',
      '微信朋友圈封面',
      '微信公众号封面',
      '微信封面设计',
      '微信文章封面',
      '微信推文封面',
      '微信营销封面',
      '微信品牌封面',
      '微信企业封面',
      '微信个人封面',
      '微信商业封面',
      '微信推广封面',
      '微信广告封面',
      '微信内容封面',
      '微信分享封面',
      '微信推荐封面',
      '微信热门封面',
      '微信爆款封面',
      '微信网红封面',
      '微信达人封面',
      '微信KOL封面',
      '微信意见领袖封面',
      '微信专家封面',
      '微信顾问封面',
    ],

    weibo: [
      'Weibo cover maker',
      'Weibo thumbnail maker',
      'Weibo poster maker',
      '微博封面制作器',
      '微博缩略图制作器',
      '微博海报制作器',
      '微博封面设计',
      '微博头像封面',
      '微博个人封面',
      '微博企业封面',
      '微博品牌封面',
      '微博营销封面',
      '微博推广封面',
      '微博广告封面',
      '微博内容封面',
      '微博分享封面',
      '微博推荐封面',
      '微博热门封面',
      '微博爆款封面',
      '微博网红封面',
      '微博达人封面',
      '微博KOL封面',
      '微博意见领袖封面',
      '微博专家封面',
      '微博顾问封面',
      '微博明星封面',
      '微博艺人封面',
      '微博歌手封面',
      '微博演员封面',
      '微博主持人封面',
      '微博记者封面',
      '微博分析师封面',
      '微博评论员封面',
      '微博博主封面',
      '微博大V封面',
    ],

    bilibili: [
      'Bilibili cover maker',
      'Bilibili thumbnail maker',
      'Bilibili poster maker',
      'B站封面制作器',
      'B站缩略图制作器',
      'B站海报制作器',
      'B站封面设计',
      'B站视频封面',
      'B站UP主封面',
      'B站个人封面',
      'B站企业封面',
      'B站品牌封面',
      'B站营销封面',
      'B站推广封面',
      'B站广告封面',
      'B站内容封面',
      'B站分享封面',
      'B站推荐封面',
      'B站热门封面',
      'B站爆款封面',
      'B站网红封面',
      'B站达人封面',
      'B站KOL封面',
      'B站意见领袖封面',
      'B站专家封面',
      'B站顾问封面',
      'B站游戏封面',
      'B站动漫封面',
      'B站音乐封面',
      'B站舞蹈封面',
      'B站美食封面',
      'B站科技封面',
      'B站生活封面',
      'B站娱乐封面',
      'B站教育封面',
    ],

    douyin: [
      'Douyin cover maker',
      'Douyin thumbnail maker',
      'Douyin poster maker',
      '抖音封面制作器',
      '抖音缩略图制作器',
      '抖音海报制作器',
      '抖音封面设计',
      '抖音视频封面',
      '抖音个人封面',
      '抖音企业封面',
      '抖音品牌封面',
      '抖音营销封面',
      '抖音推广封面',
      '抖音广告封面',
      '抖音内容封面',
      '抖音分享封面',
      '抖音推荐封面',
      '抖音热门封面',
      '抖音爆款封面',
      '抖音网红封面',
      '抖音达人封面',
      '抖音KOL封面',
      '抖音意见领袖封面',
      '抖音专家封面',
      '抖音顾问封面',
      '抖音舞蹈封面',
      '抖音音乐封面',
      '抖音美食封面',
      '抖音旅行封面',
      '抖音美妆封面',
      '抖音穿搭封面',
      '抖音健身封面',
      '抖音生活封面',
      '抖音娱乐封面',
      '抖音教育封面',
    ],
  },

  // Other social media platforms
  other: {
    snapchat: [
      'Snapchat cover maker',
      'Snapchat thumbnail maker',
      'Snapchat poster maker',
      'Snapchat story cover maker',
      'Snapchat cover image generator',
      'Snapchat poster image generator',
      'Snapchat cover creator',
      'Snapchat story cover',
      'Snapchat personal cover',
      'Snapchat business cover',
      'Snapchat brand cover',
      'Snapchat marketing cover',
      'Snapchat advertising cover',
      'Snapchat influencer cover',
      'Snapchat content creator cover',
    ],

    discord: [
      'Discord cover maker',
      'Discord thumbnail maker',
      'Discord poster maker',
      'Discord server cover maker',
      'Discord cover image generator',
      'Discord banner maker',
      'Discord poster image generator',
      'Discord cover creator',
      'Discord server cover',
      'Discord channel cover',
      'Discord community cover',
      'Discord gaming cover',
      'Discord esports cover',
      'Discord streamer cover',
      'Discord content creator cover',
    ],

    reddit: [
      'Reddit cover maker',
      'Reddit thumbnail maker',
      'Reddit poster maker',
      'Reddit subreddit cover maker',
      'Reddit cover image generator',
      'Reddit banner maker',
      'Reddit poster image generator',
      'Reddit cover creator',
      'Reddit subreddit cover',
      'Reddit community cover',
      'Reddit moderator cover',
      'Reddit admin cover',
      'Reddit user cover',
      'Reddit content creator cover',
      'Reddit influencer cover',
    ],

    telegram: [
      'Telegram cover maker',
      'Telegram thumbnail maker',
      'Telegram poster maker',
      'Telegram channel cover maker',
      'Telegram cover image generator',
      'Telegram poster image generator',
      'Telegram channel cover',
      'Telegram group cover',
      'Telegram personal cover',
      'Telegram business cover',
      'Telegram brand cover',
      'Telegram marketing cover',
      'Telegram advertising cover',
      'Telegram influencer cover',
      'Telegram content creator cover',
    ],

    whatsapp: [
      'WhatsApp cover maker',
      'WhatsApp thumbnail maker',
      'WhatsApp poster maker',
      'WhatsApp status cover maker',
      'WhatsApp cover image generator',
      'WhatsApp poster image generator',
      'WhatsApp status cover',
      'WhatsApp personal cover',
      'WhatsApp business cover',
      'WhatsApp brand cover',
      'WhatsApp marketing cover',
      'WhatsApp advertising cover',
      'WhatsApp influencer cover',
      'WhatsApp content creator cover',
      'WhatsApp story cover',
    ],
  },

  // E-commerce platforms
  ecommerce: {
    amazon: [
      'Amazon cover maker',
      'Amazon thumbnail maker',
      'Amazon poster maker',
      'Amazon product cover maker',
      'Amazon cover image generator',
      'Amazon poster image generator',
      'Amazon product cover',
      'Amazon listing cover',
      'Amazon brand cover',
      'Amazon store cover',
      'Amazon seller cover',
      'Amazon vendor cover',
      'Amazon merchant cover',
      'Amazon business cover',
      'Amazon marketing cover',
    ],

    etsy: [
      'Etsy cover maker',
      'Etsy thumbnail maker',
      'Etsy poster maker',
      'Etsy listing cover maker',
      'Etsy cover image generator',
      'Etsy poster image generator',
      'Etsy shop cover',
      'Etsy listing cover',
      'Etsy product cover',
      'Etsy brand cover',
      'Etsy seller cover',
      'Etsy vendor cover',
      'Etsy merchant cover',
      'Etsy business cover',
      'Etsy marketing cover',
    ],

    shopify: [
      'Shopify cover maker',
      'Shopify thumbnail maker',
      'Shopify poster maker',
      'Shopify product cover maker',
      'Shopify cover image generator',
      'Shopify poster image generator',
      'Shopify store cover',
      'Shopify product cover',
      'Shopify brand cover',
      'Shopify business cover',
      'Shopify marketing cover',
      'Shopify advertising cover',
      'Shopify promotion cover',
      'Shopify sale cover',
      'Shopify campaign cover',
    ],
  },

  // Professional platforms
  professional: {
    behance: [
      'Behance cover maker',
      'Behance thumbnail maker',
      'Behance poster maker',
      'Behance project cover maker',
      'Behance cover image generator',
      'Behance poster image generator',
      'Behance project cover',
      'Behance portfolio cover',
      'Behance designer cover',
      'Behance artist cover',
      'Behance creative cover',
      'Behance professional cover',
      'Behance business cover',
      'Behance brand cover',
      'Behance marketing cover',
    ],

    dribbble: [
      'Dribbble cover maker',
      'Dribbble thumbnail maker',
      'Dribbble poster maker',
      'Dribbble shot cover maker',
      'Dribbble cover image generator',
      'Dribbble poster image generator',
      'Dribbble shot cover',
      'Dribbble portfolio cover',
      'Dribbble designer cover',
      'Dribbble artist cover',
      'Dribbble creative cover',
      'Dribbble professional cover',
      'Dribbble business cover',
      'Dribbble brand cover',
      'Dribbble marketing cover',
    ],

    figma: [
      'Figma cover maker',
      'Figma thumbnail maker',
      'Figma poster maker',
      'Figma file cover maker',
      'Figma cover image generator',
      'Figma poster image generator',
      'Figma file cover',
      'Figma project cover',
      'Figma design cover',
      'Figma prototype cover',
      'Figma component cover',
      'Figma system cover',
      'Figma team cover',
      'Figma business cover',
      'Figma brand cover',
    ],
  },
};

// Helper function to get all keywords for a specific platform
export function getPlatformKeywords(platform: string): string[] {
  const platformData = PLATFORM_KEYWORDS[platform as keyof typeof PLATFORM_KEYWORDS];
  if (platformData) {
    return Array.isArray(platformData) ? platformData : [];
  }
  
  // Check nested platforms
  for (const category of Object.values(PLATFORM_KEYWORDS)) {
    if (typeof category === 'object' && !Array.isArray(category)) {
      const nestedPlatform = (category as any)[platform];
      if (nestedPlatform) {
        return nestedPlatform;
      }
    }
  }
  
  return [];
}

// Helper function to get all keywords
export function getAllKeywords(): string[] {
  const allKeywords: string[] = [];
  
  // Add core keywords
  allKeywords.push(...PLATFORM_KEYWORDS.core);
  
  // Add all platform keywords
  Object.values(PLATFORM_KEYWORDS).forEach(category => {
    if (Array.isArray(category)) {
      allKeywords.push(...category);
    } else if (typeof category === 'object') {
      Object.values(category).forEach(platformKeywords => {
        if (Array.isArray(platformKeywords)) {
          allKeywords.push(...platformKeywords);
        }
      });
    }
  });
  
  return Array.from(new Set(allKeywords)); // Remove duplicates
}















